//! Setup and diagnostic slash commands: doctor, setup, init, pricing

use anyhow::Result;

use super::*;

pub fn handle_doctor(app: &mut App, _args: &[&str]) -> Result<()> {
    let report =
        crate::cli::commands::build_doctor_report(crate::cli::commands::DoctorRuntimeContext {
            cwd: app.cwd.clone(),
            db_connected: Some(app.db.is_some()),
            provider_initialized: Some(app.provider.is_some() || app.agents.agent_loop.is_some()),
        })?;

    let mut full_report = String::from("Environment & Status:\n\n");
    full_report.push_str(&format!(
        "  Model: {}\n",
        app.model.as_deref().unwrap_or("default")
    ));
    full_report.push_str(&format!(
        "  Connected: {}\n",
        if app.agents.is_connected { "Yes" } else { "No" }
    ));
    full_report.push_str(&format!("  Messages: {}\n", app.session.messages.len()));

    let usage = &app.session.token_usage;
    full_report.push_str("\n  Tokens:\n");
    full_report.push_str(&format!("    Input:  {}\n", usage.input_tokens));
    full_report.push_str(&format!("    Output: {}\n", usage.output_tokens));
    if let Some(cost) = usage.total_cost {
        full_report.push_str(&format!("    Cost:   ${:.4}\n", cost));
    }

    full_report.push_str("\n─────────────────────────────────────────\n\n");
    full_report.push_str(&report);

    app.add_system_message(&full_report);
    Ok(())
}

pub fn handle_setup(app: &mut App, _args: &[&str]) -> Result<()> {
    use crate::config::{check_onboarding_status, format_provider_options, get_setup_instructions};

    let onboarding = check_onboarding_status();

    let mut message = String::from("d3vx Setup Wizard\n");
    message.push_str("═══════════════════════════════════════\n\n");

    if onboarding.has_api_key {
        message.push_str("API key is configured!\n");
        message.push_str(&format!(
            "  Provider: {}\n\n",
            onboarding.missing_provider.as_deref().unwrap_or("unknown")
        ));
        message.push_str("To change providers, set a new API key and restart d3vx.\n");
        app.add_system_message(&message);
        return Ok(());
    }

    message.push_str("No API key configured.\n\n");

    if let Some(provider) = &onboarding.missing_provider {
        message.push_str(&format!("Current provider: {}\n\n", provider));
        message.push_str(&get_setup_instructions(provider));
        message.push_str("\n─────────────────────────────────────────\n\n");
    }

    message.push_str("Supported Providers:\n");
    message.push_str(&format_provider_options());

    app.add_system_message(&message);
    Ok(())
}

pub fn handle_init(app: &mut App, _args: &[&str]) -> Result<()> {
    if let Some(ref cwd) = app.cwd {
        let root = std::path::Path::new(cwd);
        let ctx_dir = root.join(".d3vx");
        if !ctx_dir.exists() {
            if let Err(e) = std::fs::create_dir_all(&ctx_dir) {
                app.add_system_message(&format!("Failed to create .d3vx directory: {}", e));
                return Ok(());
            }
        }

        let ctx_file = ctx_dir.join("context.md");

        // Very basic project analysis
        let mut findings = Vec::new();
        if root.join("Cargo.toml").exists() {
            findings.push("Rust (Cargo)");
        }
        if root.join("package.json").exists() {
            findings.push("Node.js (npm/yarn/pnpm)");
        }
        if root.join("go.mod").exists() {
            findings.push("Go");
        }
        if root.join("pyproject.toml").exists() || root.join("requirements.txt").exists() {
            findings.push("Python");
        }

        let analysis = if findings.is_empty() {
            "Unknown project type".to_string()
        } else {
            findings.join(", ")
        };

        let content = format!(
            "# d3vx Project Context\n\nAutomatically generated by /init.\n\n## Detected Stack\n{}\n\n## Custom Instructions\n(Add your project-specific instructions, coding guidelines, or architecture notes here)\n",
            analysis
        );

        match std::fs::write(&ctx_file, content) {
            Ok(_) => {
                app.add_system_message(&format!(
                    "Initialized .d3vx/context.md\nDetected: {}",
                    analysis
                ));
            }
            Err(e) => {
                app.add_system_message(&format!("Failed to write context.md: {}", e));
            }
        }
    } else {
        app.add_system_message("Cannot init: no working directory set");
    }
    Ok(())
}

pub fn handle_pricing(app: &mut App, _args: &[&str]) -> Result<()> {
    app.add_system_message("Pricing info is included in /doctor. Run /doctor for full status.");
    Ok(())
}
