//! SDD workflow — top-level coordinator for the spec → plan → decompose → execute → integrate cycle
//!
//! This is the entry point for Subagent-Driven Development. It calls each
//! stage in order and manages the session state machine.

use anyhow::Result;
use tracing::info;

use crate::pipeline::approval::{ExecutionPlan, Planner};
use crate::pipeline::decomposition::DecompositionPlan;
use crate::pipeline::phases::PhaseContext;
use crate::pipeline::phases::Task;
use crate::pipeline::sdd::types::SddConfig;
use crate::pipeline::sdd::types::SddSession;
use crate::pipeline::sdd::types::SddState;

use super::decomposer::SddDecomposer;
use super::executor::{AgentProvider, SddExecutor};
use super::integrator::{IntegrationResult, SddIntegrator};
use super::plan_gate::PlanGate;
use super::spec_extractor::SpecExtractor;
pub use super::types::TaskSpec;

/// Orchestrates the full Subagent-Driven Development lifecycle.
pub struct SddWorkflow {
    config: SddConfig,
    plan_gate: PlanGate,
    decomposer: SddDecomposer,
    executor: SddExecutor,
    integrator: SddIntegrator,
}

impl SddWorkflow {
    pub fn new(
        config: SddConfig,
        plan_gate: PlanGate,
        decomposer: SddDecomposer,
        executor: SddExecutor,
    ) -> Self {
        Self {
            config,
            plan_gate,
            decomposer,
            executor,
            integrator: SddIntegrator,
        }
    }

    pub fn with_defaults(planner: Planner, provider: std::sync::Arc<dyn AgentProvider>) -> Self {
        let config = SddConfig::default();
        let gate = PlanGate::new(config.clone(), Default::default());
        Self {
            config: config.clone(),
            plan_gate: gate,
            decomposer: SddDecomposer::new(config.max_children),
            executor: SddExecutor::new(provider, config.workflow_timeout_secs),
            integrator: SddIntegrator,
        }
    }

    /// Run the full SDD workflow.
    ///
    /// This is the main entry point. Given a user request and a plan (already
    /// generated by the Plan phase handler), it:
    ///
    /// 1. Extracts a structured spec from user input
    /// 2. Runs the plan through the approval gate
    /// 3. Decomposes into child tasks (if warranted by complexity)
    /// 4. Executes children via subagents
    /// 5. Integrates and validates results
    pub async fn run(
        &self,
        user_input: &str,
        task: &Task,
        context: &PhaseContext,
        plan_text: &str,
        session: &mut SddSession,
    ) -> Result<SddResult> {
        // Step 1: Extract spec from user input
        let spec = SpecExtractor::extract(user_input);
        info!(
            scope = ?spec.scope,
            complexity = spec.estimated_complexity,
            will_decompose = spec.benefits_from_decomposition,
            "SDD spec extracted"
        );
        session.spec = Some(spec.clone());
        session
            .transition(SddState::SpecExtracted)
            .map_err(|e| anyhow::anyhow!("state error: {e}"))?;

        // Step 2: Run plan through approval gate
        let approved_plan = self
            .plan_gate
            .execute(&spec, task, context, plan_text, session)
            .await?;
        info!(plan_id = %approved_plan.id, "Plan approved");

        // Step 3: Decide whether to decompose
        if spec.benefits_from_decomposition && approved_plan.steps.len() > 1 {
            info!(
                steps = approved_plan.steps.len(),
                "Decomposing plan into child tasks"
            );
            let decomposition = self.decomposer.decompose(&approved_plan, &spec);
            session.decomposition_id = Some(format!("{}", decomposition.id));
            session
                .transition(SddState::DecompositionCreated)
                .map_err(|e| anyhow::anyhow!("state error: {e}"))?;

            // Step 4: Execute children
            let child_results = self.executor.execute(&decomposition, session).await?;

            // Step 5: Integrate results
            let integration = self
                .integrator
                .integrate(child_results, &approved_plan, session)?;

            Ok(SddResult {
                spec,
                approved_plan,
                decomposition: Some(decomposition),
                child_results: integration.child_summaries.clone(),
                integration,
            })
        } else {
            // No decomposition needed — single-agent path
            info!("Task complexity below decomposition threshold — single agent path");
            let integration = IntegrationResult {
                success: true,
                summary: "Single-agent execution — no decomposition required".into(),
                files_changed: Vec::new(),
                conflicts: Vec::new(),
                child_summaries: Vec::new(),
            };

            session
                .transition(SddState::Integrated)
                .map_err(|e| anyhow::anyhow!("state error: {e}"))?;

            Ok(SddResult {
                spec,
                approved_plan,
                decomposition: None,
                child_results: Vec::new(),
                integration,
            })
        }
    }

    /// Access config for external inspection
    pub fn config(&self) -> &SddConfig {
        &self.config
    }
}

/// Final output of a successful SDD workflow
#[derive(Debug)]
pub struct SddResult {
    /// Extracted specification
    pub spec: TaskSpec,
    /// Approved execution plan
    pub approved_plan: ExecutionPlan,
    /// Decomposition plan (None if single-agent path)
    pub decomposition: Option<DecompositionPlan>,
    /// Summaries of child agent results
    pub child_results: Vec<String>,
    /// Integration outcome
    pub integration: IntegrationResult,
}
